### PR TITLE
refactor env-achiving/env-injecting cases

### PR DESCRIPTION
**Pull request by naumvd95**

### CODE REVIEW

**Review by rkhozinov — CHANGES_REQUESTED** [review]
remove commented source

**Review by rkhozinov — CHANGES_REQUESTED** [review]
http://jenkins-tpi.bud.mirantis.net:8080/view/ui/job/10.0.ui.test_bonds/ws/iso_archive/archive/

artifacts should be stored in WORKSPACE.
we won't work with nested artifacts

**Comment by rkhozinov** [comment]
I've fixed artifacts nested. @naumvd95 please review

**Review by rkhozinov — APPROVED** [review]

**Comment by naumvd95** [comment]
@rkhozinov need to test it on ci before merging
i'll check it

**Comment by naumvd95** [comment]
Everything is awesome (looks like in one well-known song)

**Pull request merged**
