### PR TITLE
9.x/ui: green job when fail fix

### LINKED ISSUE #116: job is green when ui tests are failed
http://jenkins-tpi.bud.mirantis.net:8080/job/9.x.ui.test_nics/75/console

### PR DESCRIPTION
**Pull request by rkhozinov**
fix #116

### CODE REVIEW

**Review by ekhomyakova — APPROVED** [review]

**Review by naumvd95 — CHANGES_REQUESTED** [review]
seems we need to replace reporter-var-inject part before docker-case to get rid of redefining exit code

**Comment by ekhomyakova** [comment]
```
docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | while read code; do  
    if [ "$code" == "1" ]; then    
       exit 1
    fi
done
```

**Comment by rkhozinov** [comment]
fix #117

**Review by naumvd95 — APPROVED** [review]

**Review by naumvd95 — CHANGES_REQUESTED** [review]
your case failed (shellcheck)

seems coz of wrong defining "code" variable

https://travis-ci.org/rkhozinov/jenkins-jobs/builds/192361094
--------------------------------------------------------
here is my decision (plan B, made it just out of interest)
exit_count=$(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' ') 
if [ "$exit_count" > 0 ]; then
  exit 1;
fi
steps:
-get container IDs
-get last runs exit code for each container ID
-only non-0 status codes
-count number of non-0 status codes
-trim out white space
-Returns how many non-0 exit codes were returned. Would be 0 if everything exited with code 0.

**Review by naumvd95 — APPROVED** [review]

**Pull request merged**
